### ISSUE TITLE
Error installing Pillow while pip install livekit-plugins-openai

### ISSUE THREAD

**Issue by devacc00** [livekit/agents#1013]
Hello, once I try to install pillow 
```Collecting pillow~=10.3.0 (from livekit-agents[codecs,images]>=0.8.0.dev0->livekit-plugins-openai)
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/appleuser/work/test/agents/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/appleuser/work/test/agents/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/appleuser/work/test/agents/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/5b/sp_w2vns0rq0bcr0fb5tyj_m0000gn/T/pip-build-env-baf0d8hh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5b/sp_w2vns0rq0bcr0fb5tyj_m0000gn/T/pip-build-env-baf0d8hh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/5b/sp_w2vns0rq0bcr0fb5tyj_m0000gn/T/pip-build-env-baf0d8hh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) ➜  agents git:(main) ```

**Comment by krn-briks** [comment]
Any updates on fixing this>

**Comment by JamieBunyassi** [comment]
Change python version

**Comment by davidzhao** [comment]
what version of Python are you running? we support 3.9-3.12

**Comment by JamieBunyassi** [comment]
Works on 3.11.10

**Comment by stopdesign** [comment]
https://pypi.org/project/livekit-plugins-openai/
Requires: Python >=3.9.0
But it doesn't work with python 3.13 (because of pillow~=10.3.0 which is old).
