### ISSUE TITLE
AttributeError: 'RealtimeSession' object has no attribute '_init_sync_task'

### ISSUE THREAD

**Issue by alankashkash** [livekit/agents#1151]
This is the error I'm getting when user connects to Realtime agent.

Traceback (most recent call last):
  File "/Users/alankashkash/PycharmProjects/AIRecruit/realtime_agent/.venv/lib/python3.12/site-packages/livekit/agents/multimodal/multimodal_agent.py", line 149, in _init_and_start
    await self._session._init_sync_task
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RealtimeSession' object has no attribute '_init_sync_task' {"pid": 11867, "job_id": "AJ_nnwfvKhtFUFa"}
2024-11-29 10:42:07,347 - ERROR livekit - failed to emit event response_content_added
Traceback (most recent call last):
  File "/Users/alankashkash/PycharmProjects/AIRecruit/realtime_agent/.venv/lib/python3.12/site-packages/livekit/rtc/event_emitter.py", line 57, in emit
    callback(*callback_args)
  File "/Users/alankashkash/PycharmProjects/AIRecruit/realtime_agent/.venv/lib/python3.12/site-packages/livekit/agents/multimodal/multimodal_agent.py", line 163, in _on_content_added
    if message.content_type == "text":
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RealtimeContent' object has no attribute 'content_type'. Did you mean: 'content_index'?

Additional info:
Name: livekit-agents
Version: 0.11.3
Location: /Users/alankashkash/PycharmProjects/AIRecruit/realtime_agent/.venv/lib/python3.12/site-packages
Requires: aiodns, aiohttp, click, livekit, livekit-api, livekit-protocol, protobuf, psutil, pyjwt, types-protobuf, typing-extensions, watchfiles
Required-by: livekit-plugins-openai

Name: livekit
Version: 0.18.1
Location: /Users/alankashkash/PycharmProjects/AIRecruit/realtime_agent/.venv/lib/python3.12/site-packages
Requires: protobuf, types-protobuf
Required-by: livekit-agents

Package                Version
---------------------- ---------------
aiodns                 3.2.0
aiohappyeyeballs       2.4.3
aiohttp                3.11.7
aiosignal              1.3.1
annotated-types        0.7.0
anyio                  4.6.2.post1
attrs                  24.2.0
av                     13.1.0
certifi                2024.8.30
cffi                   1.17.1
click                  8.1.7
distro                 1.9.0
frozenlist             1.5.0
h11                    0.14.0
httpcore               1.0.6
httpx                  0.27.2
idna                   3.10
jiter                  0.7.0
livekit                0.18.1
livekit-agents         0.11.3
livekit-api            0.8.0
livekit-plugins-openai 0.10.4
livekit-protocol       0.7.0
multidict              6.1.0
openai                 1.54.3
pillow                 10.3.0
propcache              0.2.0
protobuf               5.28.3
psutil                 5.9.8
pycares                4.5.0
pycparser              2.22
pydantic               2.9.2
pydantic-core          2.23.4
pyjwt                  2.10.0
python-dotenv          1.0.1
sniffio                1.3.1
tqdm                   4.67.0
types-protobuf         5.28.3.20241030
typing-extensions      4.12.2
watchfiles             0.24.0
yarl                   1.18.0

**Comment by alankashkash** [comment]
Finally fixed by removing venv and making a new one. Leaving open for you guys if you decide to investigate it
