### ISSUE TITLE
I am facing an issue when using Azure OpenAI in function calling

### ISSUE THREAD

**Issue by narendra-bluebash** [livekit/agents#1155]
I encountered a problem where Azure OpenAI fails during function calling. Interestingly, the same functionality works correctly with OpenAI's function calling.

When this error occurs, OpenAI does not respond or speak, which is critical for my use case.

*Observed Behavior*:
When an exception is raised in Azure OpenAI function calling, no response is emitted, causing the application to remain silent.
Proposed Solution:
To address this issue, I implemented a solution in which any exception raised is explicitly emitted. This allows my code to:

*Capture the error effectively.*:
Use the voicepipeline.agent.say method to speak out the error, ensuring that the user is informed audibly when an error occurs.
*Expected Behavior*:
The application should capture the error seamlessly and respond audibly via the voicepipeline.agent.say method when an exception occurs.

**Comment by narendra-bluebash** [comment]
Error in _stream_synthesis_task
Traceback (most recent call last):
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/agents/pipeline/agent_output.py", line 273, in _stream_synthesis_task
    async for seg in tts_source:
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/agents/utils/aio/itertools.py", line 47, in tee_peer
    item = await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/agents/pipeline/pipeline_agent.py", line 869, in _llm_stream_to_str_generator
    async for chunk in stream:
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/agents/llm/llm.py", line 159, in __anext__
    raise exc from None
  File "/home/narendras/.cache/pypoetry/virtualenvs/kickcall-agents-dBnRIQRQ-py3.12/lib/python3.12/site-packages/livekit/plugins/openai/llm.py", line 563, in _main_task
    raise APIConnectionError() from e
livekit.agents._exceptions.APIConnectionError: Connection error.

**Comment by jayeshp19** [comment]
Hi @narendra-bluebash,  Is there a way to reproduce this? are you trying to call tools parallelly?

**Comment by narendra-bluebash** [comment]
Hi @jayeshp19 ,
I'm working with the tool "calling," and it works fine with OpenAI, but when using Microsoft OpenAI, sometimes it works well, and other times I get an error like "Error in _stream_synthesis_task."

I believe this happens when the tool name, like "book_appointment," is triggered. The model generates a response that goes to the TTS system, but when it tries to say "calling book_appointment," it causes an error. I suspect the TTS system can't pronounce "book_appointment" as a single word and might need it split, like "book appointment."

If GPT predicts and says "calling book appointment," it seems to work fine. My suggestion is to handle the error by emitting it when it occurs. This way, the app won't remain silent without speaking anything.

**Comment by lovemianhuatang** [comment]
I have encountered the same problem.

**Comment by robertvy** [comment]
facing a similar issue on Azure with function calling. Working with Azure deployed GPT-4o but not with GPT-4o mini where I regularly get this error when LLM tries to call a function. this is with openai plugin version v0.10.16.
