### ISSUE TITLE
AWS ECS Deployment - livekit.plugins.elevenlabs - aiodns.error.DNSError: (12, 'Timeout while contacting DNS servers')

### ISSUE THREAD

**Issue by firattamurlc** [livekit/agents#1167]
Is there anyone who encounter with this error when working with the 11labs tts ?

failed to connect to 11labs, retrying in 5s
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.12/site-packages/aiohttp/resolver.py", line 105, in resolve
    resp = await self._resolver.getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiodns.error.DNSError: (12, 'Timeout while contacting DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1317, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 946, in _resolve_host
    await future
  File "/home/appuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1002, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
      ...

**Comment by andormarkus** [comment]
Hi @firattamurlc 

Please can you simple test to determine is your problem limited to `elevenlabs.io` or you got global problem.

```python
import socket
import time


def test_dns_resolution():
    """Simple DNS resolution test using only standard library"""
    domains = ["google.com", "elevenlabs.io", "github.com"]

    print("Simple DNS Resolution Test")
    print("=========================")

    for domain in domains:
        try:
            print(f"Resolving {domain}...", end=" ")
            start_time = time.time()
            ip_address = socket.gethostbyname(domain)
            elapsed = time.time() - start_time
            print(f"SUCCESS: {ip_address} ({elapsed:.3f}s)")
        except socket.gaierror as e:
            print(f"FAILED: {e}")


if __name__ == "__main__":
    test_dns_resolution()
```
