### ISSUE TITLE
[plugin-turn-detector] exception on turn detection

### ISSUE THREAD

**Issue by CodingFu** [livekit/agents#1283]
I'm trying to run a fairly simple turn detector voice pipeline agent

I'm running python 3.13.1 on mac os (m3 chip)

```
2024-12-24 02:46:31,129 - ERROR livekit.agents - error running inference
Traceback (most recent call last):
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/agents/ipc/inference_proc_lazy_main.py", line 94, in _handle_inference_request
    data = await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/plugins/turn_detector/eou.py", line 102, in run
    text = self._format_chat_ctx(chat_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/plugins/turn_detector/eou.py", line 53, in _format_chat_ctx
    convo_text = self._tokenizer.apply_chat_template(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 1625, in apply_chat_template
    compiled_template = _compile_jinja_template(chat_template)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/transformers/utils/chat_template_utils.py", line 364, in _compile_jinja_template
    class AssistantTracker(Extension):
                           ^^^^^^^^^
NameError: name 'Extension' is not defined. Did you mean: 'Exception'? {"pid": 78999, "inference": true}
2024-12-24 02:46:31,134 - ERROR livekit.agents.pipeline - Error in _run_task
Traceback (most recent call last):
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/agents/pipeline/pipeline_agent.py", line 1234, in _run_task
    eot_prob = await self._turn_detector.predict_end_of_turn(chat_ctx)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/plugins/turn_detector/eou.py", line 183, in predict_end_of_turn
    result = await self._executor.do_inference(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingfu/src/heard/voice/.venv/lib/python3.12/site-packages/livekit/agents/ipc/job_proc_lazy_main.py", line 96, in do_inference
    raise RuntimeError(f"inference of {method} failed: {inf_resp.error}")
RuntimeError: inference of lk_end_of_utterance failed: inference of lk_end_of_utterance failed: name 'Extension' is not defined {"pid": 79006, "job_id": "AJ_7Hgjutq2GnHk"}
```

my full agent code:

```python
import asyncio
import logging

from dotenv import load_dotenv
from livekit import rtc
from livekit.agents import (
    AutoSubscribe,
    JobContext,
    JobProcess,
    WorkerOptions,
    cli,
    llm,
    metrics,
)
from livekit.agents.pipeline import VoicePipelineAgent
from livekit.plugins import openai, silero, deepgram, turn_detector

load_dotenv()
logger = logging.getLogger("voice-assistant")


def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


async def entrypoint(ctx: JobContext):
    initial_ctx = llm.ChatContext().append(
        role="system",
        text=(
            "You are a voice assistant created by LiveKit. Your interface with users will be voice. "
            "You should use short and concise responses, and avoiding usage of unpronouncable punctuation."
        ),
    )

    logger.info(f"connecting to room {ctx.room.name}")
    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)

    # wait for the first participant to connect
    participant = await ctx.wait_for_participant()
    logger.info(f"starting voice assistant for participant {participant.identity}")

    dg_model = "nova-2-general"
    if participant.kind == rtc.ParticipantKind.PARTICIPANT_KIND_SIP:
        # use a model optimized for telephony
        dg_model = "nova-2-phonecall"

    agent = VoicePipelineAgent(
        vad=ctx.proc.userdata["vad"],
        stt=deepgram.STT(model=dg_model),
        llm=openai.LLM(),
        tts=openai.TTS(),
        chat_ctx=initial_ctx,
        turn_detector=turn_detector.EOUModel(),
    )

    agent.start(ctx.room, participant)

    usage_collector = metrics.UsageCollector()

    @agent.on("metrics_collected")
    def _on_metrics_collected(mtrcs: metrics.AgentMetrics):
        metrics.log_metrics(mtrcs)
        usage_collector.collect(mtrcs)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: ${summary}")

    ctx.add_shutdown_callback(log_usage)

    # listen to incoming chat messages, only required if you'd like the agent to
    # answer incoming messages from Chat
    chat = rtc.ChatManager(ctx.room)

    async def answer_from_text(txt: str):
        chat_ctx = agent.chat_ctx.copy()
        chat_ctx.append(role="user", text=txt)
        stream = agent.llm.chat(chat_ctx=chat_ctx)
        await agent.say(stream)

    @chat.on("message_received")
    def on_chat_received(msg: rtc.ChatMessage):
        if msg.message:
            asyncio.create_task(answer_from_text(msg.message))

    await agent.say("Hey, how can I help you today?", allow_interruptions=True)


if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            prewarm_fnc=prewarm,
        ),
    )
```

**Comment by davidzhao** [comment]
Sorry for the confusion. this is due to transformers lib missing a dependency: jinja2. This is fixed in #1277 and will be released shortly in 0.3.4.

In the mean time, you can get around this error by declaring an explicit dependency to jinja2
