### ISSUE TITLE
KITT not working - latest master

### ISSUE THREAD

**Issue by anupriya17** [livekit/agents#238]
KITT example is not working throwing this exception:

```
Exception in thread Thread-2 (_write_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
{"asctime": "2024-04-13 20:00:42,152", "level": "DEBUG", "name": "root", "message": "process started", "job_id": "AJ_AUFCiWbbBkka", "url": "http://livekit-server.livekit", "pid": 92412}
failed to write log: to_bytes() missing required argument 'byteorder' (pos 2)
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/venv/lib/python3.10/site-packages/livekit/agents/apipe.py", line 49, in _write_thread
    ipc_enc.write_msg(self._p, msg)
  File "/venv/lib/python3.10/site-packages/livekit/agents/ipc_enc.py", line 45, in write_msg
    b.write(msg.MSG_ID.to_bytes(4))
TypeError: to_bytes() missing required argument 'byteorder' (pos 2)
```

**Comment by davidzhao** [comment]
Looks like this is a compatibility issue with Python 3.10. Since 3.11, `big` was the default byte order. We'll open a PR for this
