### ISSUE TITLE
Minimal Assistant Download Files error

### ISSUE THREAD

**Issue by sajkamal** [livekit/agents#284]
I get the following onnx error when trying to download files. Please help

➜ python minimal_assistant.py download-files
Using cache found in /Users/sajjadk/.cache/torch/hub/snakers4_silero-vad_master
Traceback (most recent call last):
  File "/Users/sajjadk/dev/onset_assist/agents/examples/voice-assistant/minimal_assistant.py", line 43, in <module>
    cli.run_app(WorkerOptions(request_fnc))
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/livekit/agents/cli/cli.py", line 127, in run_app
    cli()
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/livekit/agents/cli/cli.py", line 124, in download_files
    plugin.download_files()
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/livekit/plugins/silero/__init__.py", line 29, in download_files
    _ = torch.hub.load(
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/torch/hub.py", line 568, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/Users/sajjadk/dev/onset_assist/agents/myenv/lib/python3.10/site-packages/torch/hub.py", line 597, in _load_local
    model = entry(*args, **kwargs)
TypeError: silero_vad() got an unexpected keyword argument 'use_onnx'

**Comment by davidzhao** [comment]
which version of `livekit-agents` & `livekit-plugins-silero` are you using?

**Comment by davidzhao** [comment]
I see the issue. this has been fixed in main but has not yet been released. we'll get an update out shortly

**Comment by sajkamal** [comment]
Thanks David. Looking forward to running it again soon
