### ISSUE TITLE
ZeroDivisionError in voice assistant during function calling and answering

### ISSUE THREAD

**Issue by ubeytd** [livekit/agents#340]
Just tried function calling example with following  versions:

```plaintext
livekit-agents==0.7.0
livekit-plugins-openai==0.5.0
livekit-plugins-deepgram==0.5.0
livekit-plugins-elevenlabs==0.5.0
livekit-plugins-silero==0.5.0
```

When i request toggle lights, I get `ZeroDivisionError` error:

```plaintext
Task exception was never retrieved
future: <Task finished name='Task-6761' coro=<entrypoint.<locals>._answer_light_toggling() done, defined at /path/to/project/test.py:65> exception=ZeroDivisionError('float division by zero')>

Traceback (most recent call last):
  File "/path/to/project/test.py", line 80, in _answer_light_toggling
    await assistant.say(stream)
  File "/path/to/packages/livekit/agents/voice_assistant/assistant.py", line 225, in say
    await self._start_speech(data, interrupt_current_if_possible=True)
  File "/path/to/packages/livekit/agents/voice_assistant/assistant.py", line 634, in _start_speech
    await self._play_task
  File "/path/to/packages/livekit/agents/voice_assistant/assistant.py", line 712, in _play_speech_if_validated
    await _synthesize_task
  File "/path/to/packages/livekit/agents/voice_assistant/assistant.py", line 818, in _synthesize_task
    await _forward_task
  File "/path/to/packages/livekit/agents/voice_assistant/assistant.py", line 773, in _forward_stream
    tts_forwarder.mark_audio_segment_end()
  File "/path/to/packages/livekit/agents/transcription/tts_forwarder.py", line 170, in mark_audio_segment_end
    seg.avg_speed = len(self._calc_hyphenes(seg.text)) / seg.audio_duration
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

<details><summary>
Here is the `test.py` file content </summary>
<p>

```python
import asyncio
import logging
from enum import Enum
from typing import Annotated

from livekit.agents import (
    JobContext,
    JobRequest,
    WorkerOptions,
    cli,
    llm,
)
from livekit.agents.voice_assistant import AssistantContext, VoiceAssistant
from livekit.plugins import deepgram, elevenlabs, openai, silero


class Room(Enum):
    BEDROOM = "bedroom"
    LIVING_ROOM = "living room"
    KITCHEN = "kitchen"
    BATHROOM = "bathroom"
    OFFICE = "office"


class AssistantFnc(llm.FunctionContext):
    @llm.ai_callable(desc="Turn on/off the lights in a room")
    async def toggle_light(
        self,
        room: Annotated[Room, llm.TypeInfo(desc="The specific room")],
        status: bool,
    ):
        logging.info("toggle_light %s %s", room, status)
        ctx = AssistantContext.get_current()
        key = "enabled_rooms" if status else "disabled_rooms"
        li = ctx.get_metadata(key, [])
        li.append(room)
        ctx.store_metadata(key, li)

    @llm.ai_callable(desc="User want the assistant to stop/pause speaking")
    def stop_speaking(self):
        pass  # do nothing


async def entrypoint(ctx: JobContext):
    gpt = openai.LLM(model="gpt-4-turbo")

    initial_ctx = llm.ChatContext(
        messages=[
            llm.ChatMessage(
                role=llm.ChatRole.SYSTEM,
                text="You are a voice assistant created by LiveKit. Your interface with users will be voice. You should use short and concise responses, and avoiding usage of unpronouncable punctuation.",
            )
        ]
    )

    assistant = VoiceAssistant(
        vad=silero.VAD(),
        stt=deepgram.STT(),
        llm=gpt,
        tts=elevenlabs.TTS(),
        fnc_ctx=AssistantFnc(),
        chat_ctx=initial_ctx,
    )

    async def _answer_light_toggling(enabled_rooms, disabled_rooms):
        prompt = "Make a summary of the following actions you did:"
        if enabled_rooms:
            enabled_rooms_str = ", ".join(enabled_rooms)
            prompt += f"\n - You enabled the lights in the following rooms: {enabled_rooms_str}"

        if disabled_rooms:
            disabled_rooms_str = ", ".join(disabled_rooms)
            prompt += f"\n - You disabled the lights in the following rooms {disabled_rooms_str}"

        chat_ctx = llm.ChatContext(
            messages=[llm.ChatMessage(role=llm.ChatRole.SYSTEM, text=prompt)]
        )

        stream = await gpt.chat(chat_ctx)
        await assistant.say(stream)

    @assistant.on("agent_speech_interrupted")
    def _agent_speech_interrupted(chat_ctx: llm.ChatContext, msg: llm.ChatMessage):
        msg.text += "... (user interrupted you)"

    @assistant.on("function_calls_finished")
    def _function_calls_done(ctx: AssistantContext):
        logging.info("function_calls_done %s", ctx)
        enabled_rooms = ctx.get_metadata("enabled_rooms", [])
        disabled_rooms = ctx.get_metadata("disabled_rooms", [])

        if enabled_rooms or disabled_rooms:
            # if there was a change in the lights, summarize it and let the user know
            asyncio.ensure_future(_answer_light_toggling(enabled_rooms, disabled_rooms))

    assistant.start(ctx.room)
    await asyncio.sleep(3)
    await assistant.say("Hey, how can I help you today?")


async def request_fnc(req: JobRequest) -> None:
    logging.info("received request %s", req)
    await req.accept(entrypoint)


if __name__ == "__main__":
    cli.run_app(WorkerOptions(request_fnc))
``` 

</p>
</details>

**Comment by ubeytd** [comment]
`test.py` file content is : 

```python
import asyncio
import logging
from enum import Enum
from typing import Annotated

from livekit.agents import (
    JobContext,
    JobRequest,
    WorkerOptions,
    cli,
    llm,
)
from livekit.agents.voice_assistant import AssistantContext, VoiceAssistant
from livekit.plugins import deepgram, elevenlabs, openai, silero


class Room(Enum):
    BEDROOM = "bedroom"
    LIVING_ROOM = "living room"
    KITCHEN = "kitchen"
    BATHROOM = "bathroom"
    OFFICE = "office"


class AssistantFnc(llm.FunctionContext):
    @llm.ai_callable(desc="Turn on/off the lights in a room")
    async def toggle_light(
        self,
        room: Annotated[Room, llm.TypeInfo(desc="The specific room")],
        status: bool,
    ):
        logging.info("toggle_light %s %s", room, status)
        ctx = AssistantContext.get_current()
        key = "enabled_rooms" if status else "disabled_rooms"
        li = ctx.get_metadata(key, [])
        li.append(room)
        ctx.store_metadata(key, li)

    @llm.ai_callable(desc="User want the assistant to stop/pause speaking")
    def stop_speaking(self):
        pass  # do nothing


async def entrypoint(ctx: JobContext):
    gpt = openai.LLM(model="gpt-4-turbo")

    initial_ctx = llm.ChatContext(
        messages=[
            llm.ChatMessage(
                role=llm.ChatRole.SYSTEM,
                text="You are a voice assistant created by LiveKit. Your interface with users will be voice. You should use short and concise responses, and avoiding usage of unpronouncable punctuation.",
            )
        ]
    )

    assistant = VoiceAssistant(
        vad=silero.VAD(),
        stt=deepgram.STT(),
        llm=gpt,
        tts=elevenlabs.TTS(),
        fnc_ctx=AssistantFnc(),
        chat_ctx=initial_ctx,
    )

    async def _answer_light_toggling(enabled_rooms, disabled_rooms):
        prompt = "Make a summary of the following actions you did:"
        if enabled_rooms:
            enabled_rooms_str = ", ".join(enabled_rooms)
            prompt += f"\n - You enabled the lights in the following rooms: {enabled_rooms_str}"

        if disabled_rooms:
            disabled_rooms_str = ", ".join(disabled_rooms)
            prompt += f"\n - You disabled the lights in the following rooms {disabled_rooms_str}"

        chat_ctx = llm.ChatContext(
            messages=[llm.ChatMessage(role=llm.ChatRole.SYSTEM, text=prompt)]
        )

        stream = await gpt.chat(chat_ctx)
        await assistant.say(stream)

    @assistant.on("agent_speech_interrupted")
    def _agent_speech_interrupted(chat_ctx: llm.ChatContext, msg: llm.ChatMessage):
        msg.text += "... (user interrupted you)"

    @assistant.on("function_calls_finished")
    def _function_calls_done(ctx: AssistantContext):
        logging.info("function_calls_done %s", ctx)
        enabled_rooms = ctx.get_metadata("enabled_rooms", [])
        disabled_rooms = ctx.get_metadata("disabled_rooms", [])

        if enabled_rooms or disabled_rooms:
            # if there was a change in the lights, summarize it and let the user know
            asyncio.ensure_future(_answer_light_toggling(enabled_rooms, disabled_rooms))

    assistant.start(ctx.room)
    await asyncio.sleep(3)
    await assistant.say("Hey, how can I help you today?")


async def request_fnc(req: JobRequest) -> None:
    logging.info("received request %s", req)
    await req.accept(entrypoint)


if __name__ == "__main__":
    cli.run_app(WorkerOptions(request_fnc))
```

**Comment by ubeytd** [comment]
I got the same error while speaking

```powershell
Error while answering:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 672, in _play_speech_if_validated
    await data.val_ch.recv()  # wait for speech validation before playout
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/aio/channel.py", line 109, in recv
    await g
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 585, in _answer_if_validated
    await self._start_speech(data, interrupt_current_if_possible=False)
  File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 639, in _start_speech
    await self._play_task
ZeroDivisionError: float division by zero

```

**Comment by ubeytd** [comment]
Great work and thanks!🎉  It's been a game-changer for our real-time assistant project :)

**Comment by ubeytd** [comment]
Update: I haven't experienced this behavior with Elevenlabs TTS, but I do experience it with OpenAI.

**Comment by birksy89** [comment]
```
{
   "asctime":"2024-06-04 14:11:15,107",
   "level":"ERROR",
   "name":"livekit.agents",
   "message":"error while answering\nTraceback (most recent call last):\n  File \"C:\\Users\\\livekit-agents\\venv\\Lib\\site-packages\\livekit\\agents\\voice_assistant\\assistant.py\", line 585, in _answer_if_validated\n    await self._start_speech(data, interrupt_current_if_possible=False)\n  File \"C:\\Users\\livekit-agents\\venv\\Lib\\site-packages\\livekit\\agents\\voice_assistant\\assistant.py\", line 639, in _start_speech\n    await self._play_task\nZeroDivisionError: float division by zero\n",
   "taskName":"Task-14",
   "job_id":"AJ_JXJGDfLPhTwL",
   "pid":13836
}
```

Sorry, I'm a bit confused - I'm also working with elevenlabs - But it seems to fail when it jumps into a function call?

**Comment by ubeytd** [comment]
> I got the same error again while speaking long
> 
> ```powershell
> Error while answering:
> 
> Traceback (most recent call last):
>   File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 672, in _play_speech_if_validated
>     await data.val_ch.recv()  # wait for speech validation before playout
>     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/aio/channel.py", line 109, in recv
>     await g
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 585, in _answer_if_validated
>     await self._start_speech(data, interrupt_current_if_possible=False)
>   File "/path/to/anaconda3/lib/python3.11/site-packages/livekit/agents/voice_assistant/assistant.py", line 639, in _start_speech
>     await self._play_task
> ZeroDivisionError: float division by zero
> ```

Oh, sorry! 

So, the error is also occurring when the remote participant is speaking for a long time in my case. 
When I switch to elevenlabs, I have not experienced the error yet.
I did not try function calling with elevenlabs yet.

**Comment by davidzhao** [comment]
we are working on this one.. fix will be out later today

**Comment by jeffery300** [comment]
@davidzhao Please keep us posted when this is resolved and if we need to upgrade anything on our end to resolve thanks, affecting several live calls for us today cc @seanmuirhead

**Comment by ubeytd** [comment]
Great! Thanks testing now :)

**Comment by theomonnom** [comment]
I’ve just released livekit-agents==0.7.1 :)

**Comment by jeffery300** [comment]
@theomonnom We are getting audio distortion with our implementation and seeing an error here : `Error in _play_speech_if_validated_task` after updating to 0.7.1

Would love to screen share to show you what is happening if you are free, my email is jeff@assorthealth.com

**Comment by GergesBernaba1** [comment]
is this resolved?
ERROR livekit.plugins.openai.realtime - Error in _main_task
Traceback (most recent call last):
ERROR livekit.plugins.openai.realtime - OpenAI S2S error {'type': 'error', 'event_id': 'event_ANGkyIaX34YNPy9NQphGm', 'error': {'type': 'invalid_request_error', 'code': 'access_not_enabled', 'message': "Your organization does not have access to the Realtime API. We're in the process of rolling out to all developers.", 'param': None, 'event_id': None}}
