### ISSUE TITLE
silero_vad.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by devdlabs** [livekit/agents#420]
I'm testing new main version. 
When I run slightly modified version of kitt.py got this error:
```
2024-07-06 11:24:25,006 - ERROR livekit.agents - unhandled exception in the job entry <function entrypoint at 0x7fc7d0744180>
Traceback (most recent call last):
  File "/home/Projects/ava/kitt.py", line 142, in entrypoint
    vad=silero.VAD(),
        ^^^^^^^^^^^^
  File "/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/plugins/silero/vad.py", line 69, in __init__
    self._onnx_session = onnx_model.new_inference_session(force_cpu)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/plugins/silero/onnx_model.py", line 29, in new_inference_session
    session = onnxruntime.InferenceSession(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/ava/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/miniconda3/envs/ava/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/plugins/silero/resources/silero_vad.onnx failed:Protobuf parsing failed.
 {"job_id": "AJ_ZwSVGUvdna65", "pid": 10139}
 ```
 
 it seems onx model needs to be updated or Am I missing something ?

**Comment by zhoudaifa007** [comment]
The silero_vad.onnx file is managed through Git LFS (Large File Storage). When using git pull to fetch large files, there can sometimes be issues with the files being incomplete. 

the 3 follow steps may help you
1. git lfs pull ，checkout silero_vad.onnx  filesize same to origin/main
2. delete  livekit-plugins-silero sdk in virtual env path
3. pip install livekit-plugins/livekit-plugins-silero

**Comment by davidzhao** [comment]
@devdlabs you can try using the last release 0.5.3

**Comment by devdlabs** [comment]
Hi @davidzhao , Thanks for the update. After I updated Silero VAD to 0.5.3 protobuff parse error gone, but getting  TypeError: Can't instantiate abstract class VADStream without an implementation for abstract method '__aiter__'

Here is the full message:

 ```
{"message": "Error in _recognize_task", "exc_info": "Traceback (most recent call last):\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/voice_assistant/human_input.py\", line 103, in _recognize_task\n    vad_stream = self._vad.stream()\n                 ^^^^^^^^^^^^^^^^^^\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/plugins/silero/vad.py\", line 53, in stream\n    return VADStream(\n           ^^^^^^^^^^\nTypeError: Can't instantiate abstract class VADStream without an implementation for abstract method '__aiter__'", "timestamp": "2024-07-07T08:29:23.724189+00:00"}
{"message": "Error in _recognize_task\nTraceback (most recent call last):\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/voice_assistant/human_input.py\", line 103, in _recognize_task\n    vad_stream = self._vad.stream()\n                 ^^^^^^^^^^^^^^^^^^\n  File \"/home/miniconda3/envs/ava/lib/python3.12/site-packages/livekit/plugins/silero/vad.py\", line 53, in stream\n    return VADStream(\n           ^^^^^^^^^^\nTypeError: Can't instantiate abstract class VADStream without an implementation for abstract method '__aiter__'\n", "job_id": "AJ_GZkJYnFyYCXQ", "pid": 9077, "timestamp": "2024-07-07T08:29:23.727417+00:00"}
{"message": "http_session(): creating a new httpclient ctx", "timestamp": "2024-07-07T08:29:23.727978+00:00"}
{"message": "Using AsyncIOEngine.POLLER as I/O engine", "timestamp": "2024-07-07T08:29:23.992486+00:00"}

```

**Comment by devdlabs** [comment]
Tried again with updated repo, got same protobuff parse error, so manually replaced it with https://raw.githubusercontent.com/snakers4/silero-vad/master/src/silero_vad/data/silero_vad.onnx
now got ``` 

    self._event_ch = utils.aio.Chan[agents.vad.VADEvent]()
                     ^^^^^^^^^
AttributeError: module 'livekit.agents.utils' has no attribute 'aio'
 {"job_id": "AJ_pgFB2CMm2bFw", "pid": 12128}

```

**Comment by devdlabs** [comment]
@davidzhao Sorry about delay. That issue was fixed after ``` pip cache purge``` and reinstall new version.
closing this issue. Thank you.
