### ISSUE TITLE
silero stream failed

### ISSUE THREAD

**Issue by pxz2016** [livekit/agents#498]
livekit-plugins-silero  0.5.3
{"message": "silero stream failed\nTraceback (most recent call last):\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 148, in _run\n    await asyncio.shield(self._run_inference())\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 171, in _run_inference\n    raw_prob = await asyncio.to_thread(\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\asyncio\\threads.py\", line 25, in to_thread\n    return await loop.run_in_executor(None, func_call)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\concurrent\\futures\\thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 172, in <lambda>\n    lambda: self._model(tensor, self._sample_rate).item()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng/.cache\\torch\\hub\\snakers4_silero-vad_v4.0\\utils_vad.py\", line 65, in __call__\n    ort_outs = self.session.run(None, ort_inputs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py\", line 220, in run\n    return self._sess.run(output_names, input_feed, run_options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nonnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))\n", "job_id": "AJ_zdTrTVHUiSeV", "pid": 9296, "timestamp": "2024-07-24T02:06:29.405071+00:00"}

**Comment by pxz2016** [comment]
---------------------------
silero stream failed
Traceback (most recent call last):
  File "C:\Users\peng\.conda\envs\livekit\Lib\site-packages\livekit\plugins\silero\vad.py", line 148, in _run
    await asyncio.shield(self._run_inference())
  File "C:\Users\peng\.conda\envs\livekit\Lib\site-packages\livekit\plugins\silero\vad.py", line 171, in _run_inference
    raw_prob = await asyncio.to_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peng\.conda\envs\livekit\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peng\.conda\envs\livekit\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peng\.conda\envs\livekit\Lib\site-packages\livekit\plugins\silero\vad.py", line 172, in <lambda>
    lambda: self._model(tensor, self._sample_rate).item()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peng/.cache\torch\hub\snakers4_silero-vad_v4.0\utils_vad.py", line 65, in __call__
    ort_outs = self.session.run(None, ort_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peng\.conda\envs\livekit\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))
---------------------------

**Comment by pxz2016** [comment]
some warning:

2024-07-24 10:06:29.1370747 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1449686 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1516838 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1621965 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1721200 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1819278 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.1938093 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.2033842 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.2105459 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2024-07-24 10:06:29.2192252 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.

**Comment by pxz2016** [comment]
I am using it on the Windows platform and have not encountered this issue on Linux
(livekit) C:\Users\peng>pip list | findstr livekit
livekit                        0.11.1
livekit-agents                 0.7.2
livekit-api                    0.5.1
livekit-plugins-azure          0.2.1
livekit-plugins-deepgram       0.5.1
livekit-plugins-elevenlabs     0.6.0
livekit-plugins-openai         0.6.0
livekit-plugins-silero         0.5.3
livekit-protocol               0.5.1

**Comment by theomonnom** [comment]
Hey, can you update livekit-plugins-silero to 0.6.0

**Comment by theomonnom** [comment]
Closing the issue, please reopen if you're seeing this issue on the newer versions
