### ISSUE TITLE
Error when agent disconnects

### ISSUE THREAD

**Issue by egoldschmidt** [livekit/agents#564]
When the agent disconnects after finishing its audio, I see this error (I don't believe it causes any issues but I'm not quite sure).

FWIW here's how I disconnect (advice welcome if this is not the right way to do this):
```
        await voice_assistant.aclose()
        await ctx.room.disconnect()
```

Error:
```
Error in _playout_task
Traceback (most recent call last):
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/voice_assistant/cancellable_source.py", line 158, in _playout_task
    await handle._tr_fwd.aclose()
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/transcription/tts_forwarder.py", line 208, in aclose
    await self._main_atask
  File "/home/appuser/.venv/lib/python3.12/site-packages/ddtrace/contrib/asyncio/patch.py", line 50, in traced_coro
    return await coro
           ^^^^^^^^^^
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/transcription/tts_forwarder.py", line 250, in _main_task
    await forward_task
  File "/home/appuser/.venv/lib/python3.12/site-packages/ddtrace/contrib/asyncio/patch.py", line 50, in traced_coro
    return await coro
           ^^^^^^^^^^
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/agents/transcription/tts_forwarder.py", line 227, in _forward_task
    await self._opts.room.local_participant.publish_transcription(tr)
  File "/home/appuser/.venv/lib/python3.12/site-packages/livekit/rtc/participant.py", line 160, in publish_transcription
    raise PublishTranscriptionError(cb.publish_transcription.error)
livekit.rtc.participant.PublishTranscriptionError: failed to send transcription, room closed: channel closed
```

**Comment by theomonnom** [comment]
Hey, this is indeed harmless. I will take a look at ignoring these errors when the room is closed

**Comment by luiz00martins** [comment]
Is this problem solved?

I'm getting this warning on 1.1.4:
```
Traceback (most recent call last):
  File "venv\lib\site-packages\livekit\agents\voice\room_io\_output.py", line 237, in _publish_transcription
    await self._room.local_participant.publish_transcription(transcription)       
  File "venv\lib\site-packages\livekit\rtc\participant.py", line 285, in publish_transcription
    raise PublishTranscriptionError(cb.publish_transcription.error)
livekit.rtc.participant.PublishTranscriptionError: failed to send transcription, room closed: channel closed
2025-07-17 03:45:20,274 - WARNING livekit.agents - failed to publish transcription

Traceback (most recent call last):
  File "venv\lib\site-packages\livekit\agents\voice\room_io\_output.py", line 361, in capture_text
    self._writer = await self._create_text_writer()
  File "venv\lib\site-packages\livekit\agents\voice\room_io\_output.py", line 337, in _create_text_writer
    return await self._room.local_participant.stream_text(
  File "venv\lib\site-packages\livekit\rtc\participant.py", line 578, in stream_text
    await writer._send_header()
  File "venv\lib\site-packages\livekit\rtc\data_stream.py", line 189, in _send_header
    raise ConnectionError(cb.send_stream_header.error)
ConnectionError: engine: connection error: engine is closed
2025-07-17 03:45:20,542 - WARNING livekit.agents - failed to publish transcription
```
