### ISSUE TITLE
AssertionError: assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))

### ISSUE THREAD

**Issue by AutoScrape123TX** [livekit/agents#872]
Got an error at the end of a `JobContext` worker instance.

Everything goes well until the close of the `Worker`.

I tried many things and nothing does the trick...

```
if __name__ == "__main__":
    settings = Settings()
    # https://docs.livekit.io/agents/build/anatomy/
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            request_fnc=request_fnc,
            prewarm_fnc=prewarm_fnc,
            api_key=settings.livekit_api_key,
            api_secret=settings.livekit_api_secret,
            ws_url=settings.livekit_ws_url,
            initialize_process_timeout=30.0,
            shutdown_process_timeout=180.0,
            num_idle_processes=1
        )
    )
```

```
def prewarm_fnc(j_proc: JobProcess) -> None:
    j_proc.userdata["transcriber_config"] = transcriber_config
    j_proc.userdata["agent_config"] = agent_config
    j_proc.userdata["agent_summary_config"] = agent_summary_config
    j_proc.userdata["synthesizer_config"] = synthesizer_config
    j_proc.userdata["elevenlabs_history_manager"] = elevenlabs_history_manager
    j_proc.userdata["logger"] = logger

    j_proc.userdata["sip_api_client"] = sip_api_client

async def entrypoint(ctx: JobContext):
    output_device = LiveKitOutputDevice(
        sampling_rate=8000,
        audio_encoding=AudioEncoding.MULAW
    )
    conversation = LiveKitConversation(
        output_device=output_device,
        transcriber=DeepgramTranscriber(
            transcriber_config=ctx.proc.userdata["transcriber_config"],
            logger=ctx.proc.userdata["logger"]
        ),
        agent=ChatGPTAgent(
            agent_config=ctx.proc.userdata["agent_config"],
            logger=ctx.proc.userdata["logger"]
        ),
        agent_summary=ChatGPTAgent(
            agent_config=ctx.proc.userdata["agent_summary_config"],
            logger=ctx.proc.userdata["logger"]
        ),
        synthesizer=ElevenLabsSynthesizer(
            synthesizer_config=ctx.proc.userdata["synthesizer_config"],
            synthesizer_history_manager=ctx.proc.userdata["elevenlabs_history_manager"],
            logger=ctx.proc.userdata["logger"]
        ),
        logger=ctx.proc.userdata["logger"]

    )

    async def shutdown_hook():
        ""

    ctx.add_shutdown_callback(shutdown_hook)

    await conversation.start_room(ctx=ctx)
    # wait_task = asyncio.create_task(wait_for_termination(conversation, ctx))
    await wait_for_termination(conversation, ctx)

async def wait_for_termination(conversation: LiveKitConversation, ctx: JobContext):
    await conversation.wait_for_termination()
    await conversation.terminate()

    await ctx.room.disconnect()
    ctx.shutdown(reason="Session ended")
    """print("deconnect")
    if ctx.room.isconnected():
        await ctx.room.disconnect()"""

    """print("del")
    del ctx.proc.userdata["transcriber_config"]
    del ctx.proc.userdata["agent_config"]
    del ctx.proc.userdata["agent_summary_config"]
    del ctx.proc.userdata["synthesizer_config"]
    del ctx.proc.userdata["elevenlabs_history_manager"]
    del ctx.proc.userdata["logger"]
    del ctx.proc.userdata["sip_api_client"]
    print("fidel")
    ctx.shutdown()"""
```

Even with deleting data, not shutting down `JobContext`, not disconnect from `Room`, etc...

I didn't find why this handle deleting is failing...

ERROR : 
```
Exception ignored in: <function FfiHandle.__del__ at 0x7f05083d2660>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 90, in __del__
    self.dispose()
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 99, in dispose
    assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Exception ignored in: <function FfiHandle.__del__ at 0x7f05083d2660>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 90, in __del__
    self.dispose()
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 99, in dispose
    assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Exception ignored in: <function FfiHandle.__del__ at 0x7f05083d2660>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 90, in __del__
    self.dispose()
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 99, in dispose
    assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Exception ignored in: <function FfiHandle.__del__ at 0x7f05083d2660>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 90, in __del__
    self.dispose()
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 99, in dispose
    assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Exception ignored in: <function FfiHandle.__del__ at 0x7f05083d2660>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 90, in __del__
    self.dispose()
  File "/root/.cache/pypoetry/virtualenvs/telephony-app-3ztbhrtE-py3.12/lib/python3.12/site-packages/livekit/rtc/_ffi_client.py", line 99, in dispose
    assert ffi_lib.livekit_ffi_drop_handle(ctypes.c_uint64(self.handle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 

```

**Comment by theomonnom** [comment]
This has been fixed by https://github.com/livekit/rust-sdks/pull/460
I've just released livekit-agents==0.10.1 that contains this fix
