### ISSUE TITLE
Is this a realtime_model.py error？

### ISSUE THREAD

**Issue by Kael-DWT** [livekit/agents#903]
```
2024-10-12 17:03:08,106 - ERROR livekit.plugins.openai.realtime - Error in _run_fnc_task
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chatwaysway-BnmJShFr-py3.11/lib/python3.11/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatwaysway-BnmJShFr-py3.11/lib/python3.11/site-packages/livekit/plugins/openai/realtime/realtime_model.py", line 1160, in _run_fnc_task
    await called_fnc.task
AttributeError: 'coroutine' object has no attribute 'points' {"pid": 3347405, "job_id": "AJ_PzgLUFB9UoTt"}
```

**Comment by steinathan** [comment]
Hey, im having this same error, i see it was closed by you - please how did you solve it?
